### ISSUE TITLE
unable to purchase ticket in Ústí nad Labem

### ISSUE THREAD

**Issue by jiri-bati-novak** [avast/sms-ticket#20]
see subj. the application sends SMS, but does not get reply - incoming SMS is not recognized, the app displays "rotating coin" forever and ever.

**Comment by davidvavra** [comment]
Hi, what version of Android do you have? Do you use some third-party apps for receiving SMS messages?

**Comment by jiri-bati-novak** [comment]
I found this this bug on android 4.2 and 5.1... 4.2 use no third party app
(it's old prestigio phone), 5.1 is CyanogenMOD and uses hangouts for
receiving sms...
Jiri Novak

2015-07-13 15:49 GMT+02:00 David Vavra notifications@github.com:

> Hi, what version of Android do you have? Do you use some third-party apps
> for receiving SMS messages?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/avast/sms-ticket/issues/20#issuecomment-120933803.

## 

Jiří Novák

**Comment by TomasKypta** [comment]
Hi, there's no guarantee that an app will receive a SMS on Android pre 4.4.
We can send it but, we might not be able to tell if something comes.
That's because other apps can "steal" the incoming SMS 
(it's AN ordered broadcast and they can cancel it).

Even though you don't have a third party app on the Prestigio phone, 
it might be the case that a system messaging app does the stealing.

And Cyanogen is bit problematic, that non-standard system,
you can't guarantee anything there.

**Comment by jiri-bati-novak** [comment]
Okay, I get your point, but that does not explain why the app was working
fine on both devices about month ago. Also other apps using sms f.ex. for
the authentication and also "stealing" incoming messages work flawlessly.
Maybe a bug in the tickets definitions.
But obviously you don't care about finding the solution, sorry to hear
that. Finding a challenge oriented developer is hard in those times...
Dne 13. 7. 2015 9:14 PM napsal uživatel "Tomas Kypta" <
notifications@github.com>:

**Comment by TomasKypta** [comment]
If it was working, then the problem is elsewhere!
It might really be a problem with the SMS format (outgoing or incoming).
When you send the message, does any other app (messaging app) receive your sms ticket? 
If so, could you give us a received message so we can adjust the parsing format?
Finding a precise bug report is even harder in those times…

**Comment by jiri-bati-novak** [comment]
Well, if it wasn't working, I would not even bother you with a bug report,
I would just dismiss it as an app vs. os version/brand incompatibility and
moved on.
Yes, the message is sent, and correct answer (ticket receipt) is received
in messaging app, so apparently there is something wrong with the incoming
message parsing, which I thought was mentioned in the first report, and I
apologize if it wasn't clear. As I moved on to using another app for
obtaining tickets (sejf, to be precise, as it eliminates the cost of sms),
I don't have any incriminating message handy, but I'll try the other phone
(4.2 Prestigio) and if I do find any of those still in messaging app, I'll
send them ASAP.
Well, last words - don't get me wrong, I am not trying to mock you or
lessen your work, but at least pre-filled e-mail template with a
questionaire regarding the bug (á la bugzilla) would be nice addition and
would give you much detailed and complete bug reports. Howgh :-)

2015-07-13 23:46 GMT+02:00 Tomas Kypta notifications@github.com:

> If it was working, then the problem is elsewhere!
> It might really be a problem with the SMS format (outgoing or incoming).
> When you send the message, does any other app (messaging app) receive your
> sms ticket?
> If so, could you give us a received message so we can adjust the parsing
> format?
> Finding a precise bug report is even harder in those times…
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/avast/sms-ticket/issues/20#issuecomment-121070518.

## 

Jiří Novák

**Comment by jiri-bati-novak** [comment]
This is how correct reply SMS looks:
Nur5nBy2V/727867/Dfw DP m. Usti n/L a.s. Jizdenka prestupni 20,- Kc,
Platnost od: 4.7.15 15:09 do: 4.7.15 16:09 Plati v zone 101, mimo linku 456.
Dne 14. 7. 2015 8:49 napsal uživatel "Jiří Novák" <jiri.bati.novak@gmail.com

**Comment by davidvavra** [comment]
I have updated SMS format for Usti in git, it will be soon updated in the app. Thanks for reporting.
