### ISSUE TITLE
Date select in statistics does not work

### ISSUE THREAD

**Issue by paulslaby** [avast/sms-ticket#24]
When you hit set date in Statictics, it sets today not the date you selected.

**Comment by davidvavra** [comment]
@paulslaby I tried it today and it works on my phone. What version of Android do you have? Can you post some screenshot?

**Comment by paulslaby** [comment]
When I hit "Nastavit", today is selected, as you can see in the second picture. 
https://cloud.githubusercontent.com/assets/1090074/12146268/0ed67ed6-b493-11e5-8f7e-f1a03bf0ebba.png 
https://cloud.githubusercontent.com/assets/1090074/12146269/0ed955e8-b493-11e5-8eac-cb521a3838ac.png
App version: 3.2.1
Android version: 5.0.1

**Comment by davidvavra** [comment]
@paulslaby I still can't reproduce it. I'm working on a new update, dialogs are little different there, can you please try if it helps?
https://www.dropbox.com/s/xde77uaxf7ccsbo/sms-ticket-mobile-3.3.0-300025-f89fbb7-release.apk?dl=0
