### ISSUE TITLE
Time format doesn't respect system setting

### ISSUE THREAD

**Issue by MichalJungmann** [avast/sms-ticket#26]
App shows times in 12-hour format ("AM/PM") although the phone is set to use 24-hour format.

App shall respect system setting of time format and/or add its own option to set 12/24-hour time format.

All versions up to newest 3.3.1 @ Nexus 4 (v5.1.1., build LMY48T).

![screenshot_2016-01-16-11-28-04](https://cloud.githubusercontent.com/assets/16732149/12372104/e2777d5c-bc4b-11e5-9907-26e861b44e16.png)
![screenshot_2016-01-16-12-20-01](https://cloud.githubusercontent.com/assets/16732149/12372105/e4e457ea-bc4b-11e5-8b64-23db129dadcf.png)

**Comment by davidvavra** [comment]
I tried it today on Nexus 5 with Android 6.0 and it works as expected - it respects system setting on 24-hour date. The app relies on Android to format dates. So I guess it was some Android bug which is now fixed.
