### ISSUE TITLE
Application doesn't recognize the received ticket - Ostrava

### ISSUE THREAD

**Issue by liballuk** [avast/sms-ticket#29]
I attach present format.
![jizdenka ostrava](https://cloud.githubusercontent.com/assets/10846051/13919650/0863a878-ef6f-11e5-9675-969f2117b5d3.jpg)

**Comment by davidvavra** [comment]
Would you like to send a pull request which fixes this? You can look into recent pull request which fixed ticket in Brno for inspiration: https://github.com/avast/sms-ticket/pull/28

**Comment by TomasKypta** [comment]
Hi, I'm already working on it. Should be fixed soon.

**Comment by TomasKypta** [comment]
Should be fixed.
