### ISSUE TITLE
Update ticket definitions for Hradec Kralove

### ISSUE THREAD

**Issue by pavkriz** [avast/sms-ticket#38]
Please update ticket definitions for Hradec Kralove according to http://www.dpmhk.cz/cs/mhd-hradec-kralove/mobilni-jizdenka/objednani-pomoci-sms

**Comment by davidvavra** [comment]
Hi, you can do it yourself as described here: https://github.com/avast/sms-ticket#how-to-add-a-new-city-or-modify-data-about-tickets
Send a pull request after that.

**Comment by TomasKypta** [comment]
I'm on it.
